### ISSUE TITLE
Why not separate repos?

### ISSUE THREAD

**Issue by BrianHicks** [elm-community/literature-reviews#1]
As far as library additions, it makes sense to put research summaries / literature reviews close to the code being worked on.

If this is *just* for language extensions, maybe the README should say that?

Yes, I know there's a lot of context I'm ignoring from elm-discuss in opening this issue, but the README is going to be the first thing that most people see here going forward.

P.S.: I've tried to make this the least confrontational I can without dropping the point. If it's unclear, I'm not trying to drag the effort. I think it's great! But let's be *really* clear about what this is for.

**Comment by eeue56** [comment]
Discoverability. Exploring language extensions is mostly theoretical. As a result, all the proposed language extensions should just be co-located for easy discovering, just as the PEPs are for Python.

**Comment by BrianHicks** [comment]
So then are "library additions" more about adding things to the Core package than they are proposals for community packages?

**Comment by opsb** [comment]
The Elm platform includes Elm the language, Elm the framework and all of the web APIs. They're all directly under Evan's control at the moment so it makes sense to have a single, structured form of communication. It's definitely worth defining the scope in the README, does "Elm the language, Elm the framework and all of the web APIs" seem appropriate?

**Comment by BrianHicks** [comment]
What do you mean by "framework"… The Elm Architecture?

Otherwise, that looks mostly good! How about spelling it out more explicitly… something like this?

> Proposals, research gathering, and literature review for:
>
> - Extensions to the Elm language, syntax, and semantics.
> - Modifications or extensions of the core Elm packages, meaning the elm "standard library" which includes things like `List`, `Dict`, and `Json.Decode`.
> - Large community-focused informational documents (why do we do it *that* way?)
>
> These documents are modeled after the spirit of the [Python Enhancement Proposals](https://www.python.org/dev/peps/pep-0001/).

**Comment by mgold** [comment]
I agree that both language features and core API changes are on the table. I like Brian's suggested text except for the link to PEP. I think we should define what this is ourselves before saying it's modeling after a particular process in another community. I'd be happy to include a section in the README with links to many such processes; open another issue.

The other reason is that I want to steer this away from implementation, even if it's a library addition. (Take that to *-extra libraries.) I think most of those code that lives in this repo will be example apps.

**Comment by BrianHicks** [comment]
That's totally fair. I will make a PR and we can tweak it further over there.

**Comment by BrianHicks** [comment]
#6 is merged, resolving my original question. If there are any more, open more issues!
