### ISSUE TITLE
Help by gathering resources in issues?

### ISSUE THREAD

**Issue by mpizenberg** [elm-community/literature-reviews#8]
Since doing a full literature review is hard work, I (like many others I guess) do not feel like starting one right now. I can however help in the process by referencing links to discussions, posts, ... with regard to some literature review. To be more concrete, I will take one example: support for binary data types (array buffers etc.).

What I could do for example is create an issue (with title "Binary data types support") and start list references like this:

1. Elm discuss - [Collecting use cases for File, ArrayBuffer and TypedArrays/DataViews](https://groups.google.com/forum/#!topic/elm-discuss/u_ui3PlDwLc)
2. ...

What do you think of this approach? Do you think it is valuable at all? Are issues the best medium to do this?

**Comment by BrianHicks** [comment]
You don't have to do a *full* literature review. Just fill the template out and start adding references. Opening issues like this is a good way to collaborate; it will keep everything in one place.

**Comment by BrianHicks** [comment]
The process is documented now, see https://github.com/elm-community/literature-reviews#the-process. If that doesn't work for you, please open another issue about specifically what's wrong. Thanks!
