### ISSUE TITLE
Binary data types support

### ISSUE THREAD

**Issue by mpizenberg** [elm-community/literature-reviews#9]
# Binary data types support

- Steward: {Your Name} {you@example.com}, {@you} on the Elm Slack
- Questions + Collaboration: {room} on the Elm Slack

Define your feature. What will you be able to do if it's implemented? Define the main pieces of terminology. If applicable, define what it is *not*.

## Motivation

Why is this feature useful? Why do you want it in Elm?

This feature is required anytime needing to manipulate files, array buffers, send binary encoded data through http, ...

## Current best practice

Describe the best way(s) of doing what you want to do in Elm today. This can include prose, code snippets, or a link to a working example within this repo. Discuss what makes this situation less than ideal.

## Use cases from real projects

Elm features are only added once it's been proven that they solve a problem the occurs in real projects. The more example use cases that are made available the better the final design will be. It's important that these aren't hypothetical scenarios or toy problems, they need to be from real projects that developers are working on.

## Literature review

How do other langues implement this feature or address this problem? Be sure to look at other ML-family langues (e.g. Haskell, OCaml, F#) and the JavaScript ecosystem.

What approachs work well? Which ones do not? Have other communities written design documents or retrospectives on this feature?

## Proposed API or syntax

Briefly and provisionally describe a library API or language syntax for the feature. Connect the API with the design goals established above.

## References

* [Support for binary data][elm-discuss-2016-01-11]
* [Announce: Native binary serialization generators from protocol buffers][elm-discuss-2016-03-23]
* [Collecting use cases for File, ArrayBuffer and TypedArrays/DataViews][elm-discuss-2016-07-29]
* [Collecting design ideas for File/FileReader, ArrayBuffer and TypedArrays/DataViews][elm-discuss-2016-08-16]

[elm-discuss-2016-01-11]: https://groups.google.com/d/topic/elm-discuss/spr621OlUeo/discussion
[elm-discuss-2016-03-23]: https://groups.google.com/d/topic/elm-discuss/4jOpKeBs7yo/discussion
[elm-discuss-2016-07-29]: https://groups.google.com/forum/#!topic/elm-discuss/u_ui3PlDwLc
[elm-discuss-2016-08-16]: https://groups.google.com/d/topic/elm-discuss/fVFXqEHpxAQ/discussion

**Comment by mpizenberg** [comment]
Hi all, so this repository is an attempt at making a coherent literature reviews of missing elm features. Please go have a look at the readme, contributing guide and template if your new here.

This specific issue focus on **binary data types support in elm**. I'm personally neither very experienced in functional programming nor in web development (mostly doing research in image processing). So I don't feel like carrying the "Steward" label. But I thought I could contribute a little by pointing out to some references out there.

I've mentionned you here because you manifested your interest in some of the discussions listed above in references. Sorry in advance if I made a mistake or if you're not interested anymore (I figured Duane you can always unfollow). If you feel like becoming the "Steward", please say so. Also, if you can help in filling the template above in the issue, go forward!

PS: I don't think I have the rights to open a slack discussion about this (or I did not find how). If anyone here can, it could be helpful :)

@danyx23 @newlandsvalley @pdamoc @weitzj @eriklott @zkessin @wpiekutowski @quexxon @prozacchiwawa @jesseilev @ccapndave @ianmackenzie @gaborv @johnpmayer @jinjor @bgourlie @martindemello @canadaduane @simonh1000 @polux @mapmarkus

**Comment by eeue56** [comment]
Please do not just ping everyone.

**Comment by BrianHicks** [comment]
There's a documented process now! (https://github.com/elm-community/literature-reviews#the-process) It would be super helpful if you could resubmit this as a PR. Go ahead and replace the template parts with what you know, and we'll work together to get the rest.

In particular, you're coordinating the work so you're already acting as the steward. Surprise, you're awesome! Go ahead and fill in your name as the steward when you submit the PR. It's not like you're getting "binary blobs" tattooed on your forehead by doing this; the steward can change.

I'm going to close and lock this issue now since *allll* those people are going to get pinged every time there's a new comment. Feel free to ask me more questions on Elm Slack (same username) or on a new issue.
